### ISSUE TITLE
Create examples of commonly used HMMs

### ISSUE THREAD

**Issue by nipunbatra** [jmschrei/yahmm#1]
Would be good to have some complete code snippets for commonly used HMM examples, such as the following:
#### Discrete emission HMMs
1. [Rainy-sunny example](http://en.wikipedia.org/wiki/Hidden_Markov_model) from Wikipedia
#### Continuous emission HMMs
1. Density mixtures

Maybe even an illustrative example of each type from [Bayes Net toolbox](http://bnt.googlecode.com/svn/trunk/docs/usage_dbn.html)
![hmm_io](https://cloud.githubusercontent.com/assets/60985/2872367/fc3726e0-d35c-11e3-909d-875c3fcad1e3.gif)
![hmm_coupled](https://cloud.githubusercontent.com/assets/60985/2872368/fc480942-d35c-11e3-8a57-bd901ea2150c.gif)
![hmm_factorial](https://cloud.githubusercontent.com/assets/60985/2872369/fc57b2de-d35c-11e3-8249-64323c7f202f.gif)
![hmm_mixgauss](https://cloud.githubusercontent.com/assets/60985/2872363/bae76768-d35c-11e3-9157-4a248fce5040.gif)

**Comment by jimwilluk** [comment]
Hi, I am working on building a fhmm based on yahmm and have the same question. Was this resolved?

Thanks

**Comment by jmschrei** [comment]
Hello!

YAHMM currently does not support factorial HMMs, actually. I had misunderstood what a FHMM was. When I have more development time, I am considering adding support, but I do not know when exactly that will be. Also, all new development is being done on pomegranate, which YAHMM has merged with.

If you can recommend a clear resource on learning about FHMMs, that would speed up the process!
