### ISSUE TITLE
Very slow training with multivariate normal distributions 

### ISSUE THREAD

**Issue by matthiasplappert** [jmschrei/yahmm#45]
I'm trying to use yahmm to classify motions. Each motion has approx. 12.000 samples, where each sample has 43 features. I use 10 states for the HMM, each with a multivariate Gaussian distribution. The code that I use to create states looks something like this:

```
# Add states
std = np.sqrt(np.abs(covar.diagonal()))
normals = [[yahmm.NormalDistribution(mean[i], std[i]) for i in range(n_features)] for _ in range(n_states)]
distributions = [yahmm.MultivariateDistribution(normals[i]) for i in range(n_states)]
states = [yahmm.State(distributions[i]) for i in range(n_states)]
model.add_states(states)
```

However, once I try to train the model with baum-welch, the performance tanks. After having a look at the implementation, this is not really a surprise since every distribution is trained separately. Is there anything I can do to speed this up? I have even debated to implement my own `MultivariateNormalDistribution` class to make the training more efficient, but wanted to ask here first for help.

Any input is greatly appreciated!

**Comment by matthiasplappert** [comment]
Here's the output from training a classifier that uses 3 HMMs internally on a training set of size :

```
Training classifier ...
Training improvement: 10182.3571103
Training improvement: 4929.05362618
Training improvement: 2271.92379194
Training improvement: 1501.1805278
Training improvement: 122.853310171
Training improvement: -24.8714463425
Total Training Improvement:  18982.49692
Training improvement: 3900.36011849
Training improvement: 1022.41232959
Training improvement: 1568.01129329
Training improvement: 4690.87996001
Training improvement: 4550.62389231
Training improvement: 2220.77991185
Training improvement: 1453.63227404
Training improvement: 341.736518179
Training improvement: 422.338628506
Training improvement: 297.823477725
Training improvement: 353.227748233
Training improvement: 304.771641819
Training improvement: 343.53272939
Training improvement: 356.821458624
Training improvement: 383.062855323
Training improvement: 2699.26950382
Training improvement: 2296.17086845
Training improvement: 675.975334689
Training improvement: 664.899948778
Training improvement: 458.501370152
Training improvement: 507.172111823
Training improvement: 489.643016868
Training improvement: 392.143036856
Training improvement: 33.4617738517
Training improvement: -40.7470307316
Total Training Improvement:  30386.5047719
Training improvement: 3206.51672701
Training improvement: 60.8408854307
Training improvement: 2309.85021154
Training improvement: 5279.57361157
Training improvement: 3722.26162541
Training improvement: 768.20733531
Training improvement: 460.802692531
Training improvement: -234.430244814
Total Training Improvement:  15573.622844
Classifier trained, took 118.015823 seconds
```

The whole process takes xx seconds. Also note that for the second HMM, baum-welch seems to converge very slowly. The training was performed on an Intel Core i7-4790 CPU @ 3.60GHz × 8

**Comment by jmschrei** [comment]
Howdy

Sorry about responding late, I've had an ever expanding queue of things to do.

You might be looking for MultivariateGaussianDistribution, where you learn a mean vector and full covariance matrix. This isn't implemented in yahmm, but is in pomegranate, which I am actively developing. You should consider using that if you want to speed up training, as the vectorized calculations are faster. I'm about to push a commit tonight updating it allowing you to learn either a full covariance matrix or just the diagonal for independent distributions. 

As for the comparison, that does seem like poor performance on yahmm's part. I believe you've identified a good reason why it's slow--updating all of these distributions serially. Using the distribution mentioned above should help with this. Another idea which comes to mind is that the two packages probably have different termination conditions. A commonly used convergance criterion is when you don't improve by more than some percent of the first improvement, and going from 3206 to 60 is a pretty big drop. 

If you can run your script using a <a href="https://docs.python.org/2/library/profile.html">profiler</a> and sort by cumulative time I can take a look and make modifications to pomegranate which help you out on yahmm's end.

**Comment by matthiasplappert** [comment]
Thanks for the response! I've started to look into pomegranate but ran into a problem: https://github.com/jmschrei/pomegranate/issues/6

I'll also do some profiling once I get it to run with the multivariate Gaussian.

I presume that moving forward I should probably prefer pomegranate over yahmm, right?

**Comment by jmschrei** [comment]
That would be preferable. I'm not doing active development for yahmm, but I will be for pomegranate.
