### ISSUE TITLE
Numpy import error in _log_probability()

### ISSUE THREAD

**Issue by rpryzant** [jmschrei/yahmm#47]
When I call `log_probability()` on a `yahmm.Model`, I get the following error:

```
Exception NameError: "global name 'np' is not defined" in 'yahmm.yahmm.Model._log_probability' ignored
```

Please let me know if there's any more info I could send your way.

**Comment by jmschrei** [comment]
Howdy @rpryzant . I'm not sure what's up with that error, but you should switch over to using pomegranate, which is a superset of yahmm that is likely much faster. All you need to do to change your code is change `from yahmm import Model` to `from pomegranate import HiddenMarkovModel`. If you encounter any issues switching over, you should open an issue over there.

**Comment by rpryzant** [comment]
Awesome thank you.
